# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generateTestbedDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenerateTestbedDialog(object):
    def setupUi(self, GenerateTestbedDialog):
        GenerateTestbedDialog.setObjectName("GenerateTestbedDialog")
        GenerateTestbedDialog.resize(500, 526)
        self.verticalLayout = QtWidgets.QVBoxLayout(GenerateTestbedDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(GenerateTestbedDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.areaWidthLe = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaWidthLe.sizePolicy().hasHeightForWidth())
        self.areaWidthLe.setSizePolicy(sizePolicy)
        self.areaWidthLe.setObjectName("areaWidthLe")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.areaWidthLe)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.areaHeightLe = QtWidgets.QLineEdit(self.groupBox)
        self.areaHeightLe.setObjectName("areaHeightLe")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.areaHeightLe)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.numNodesLe = QtWidgets.QLineEdit(self.groupBox)
        self.numNodesLe.setObjectName("numNodesLe")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.numNodesLe)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.minDistLe = QtWidgets.QLineEdit(self.groupBox)
        self.minDistLe.setObjectName("minDistLe")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.minDistLe)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(300, 0))
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.minPRRLe = QtWidgets.QLineEdit(self.groupBox)
        self.minPRRLe.setMinimumSize(QtCore.QSize(150, 0))
        self.minPRRLe.setObjectName("minPRRLe")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.minPRRLe)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(GenerateTestbedDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.noisefloorLe = QtWidgets.QLineEdit(self.groupBox_2)
        self.noisefloorLe.setObjectName("noisefloorLe")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.noisefloorLe)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txpowerLe = QtWidgets.QLineEdit(self.groupBox_2)
        self.txpowerLe.setObjectName("txpowerLe")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txpowerLe)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.wavelengthLe = QtWidgets.QLineEdit(self.groupBox_2)
        self.wavelengthLe.setObjectName("wavelengthLe")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wavelengthLe)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setMinimumSize(QtCore.QSize(300, 0))
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.fsplExpLe = QtWidgets.QLineEdit(self.groupBox_2)
        self.fsplExpLe.setMinimumSize(QtCore.QSize(150, 0))
        self.fsplExpLe.setObjectName("fsplExpLe")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fsplExpLe)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(GenerateTestbedDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.snrLbl = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.snrLbl.setFont(font)
        self.snrLbl.setText("")
        self.snrLbl.setObjectName("snrLbl")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.snrLbl)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.rxsenLbl = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rxsenLbl.setFont(font)
        self.rxsenLbl.setText("")
        self.rxsenLbl.setObjectName("rxsenLbl")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rxsenLbl)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setMinimumSize(QtCore.QSize(300, 0))
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.maxDistLbl = QtWidgets.QLabel(self.groupBox_3)
        self.maxDistLbl.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxDistLbl.setFont(font)
        self.maxDistLbl.setText("")
        self.maxDistLbl.setObjectName("maxDistLbl")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxDistLbl)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(GenerateTestbedDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GenerateTestbedDialog)
        self.buttonBox.accepted.connect(GenerateTestbedDialog.accept)
        self.buttonBox.rejected.connect(GenerateTestbedDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GenerateTestbedDialog)

    def retranslateUi(self, GenerateTestbedDialog):
        _translate = QtCore.QCoreApplication.translate
        GenerateTestbedDialog.setWindowTitle(_translate("GenerateTestbedDialog", "Generate Testbed"))
        self.groupBox.setTitle(_translate("GenerateTestbedDialog", "Testbed settings"))
        self.areaWidthLe.setText(_translate("GenerateTestbedDialog", "100"))
        self.label.setText(_translate("GenerateTestbedDialog", "Area width [m]"))
        self.areaHeightLe.setText(_translate("GenerateTestbedDialog", "100"))
        self.label_2.setText(_translate("GenerateTestbedDialog", "Area height [m]"))
        self.label_3.setText(_translate("GenerateTestbedDialog", "Number of nodes"))
        self.numNodesLe.setText(_translate("GenerateTestbedDialog", "32"))
        self.label_4.setText(_translate("GenerateTestbedDialog", "Min. node distance [m]"))
        self.minDistLe.setText(_translate("GenerateTestbedDialog", "1.4142"))
        self.label_5.setText(_translate("GenerateTestbedDialog", "Min. PRR between nearest neighbors"))
        self.minPRRLe.setToolTip(_translate("GenerateTestbedDialog", "Determines how far away nodes can be placed. There should be at least one neighbor with a PRR >= the specified value."))
        self.minPRRLe.setText(_translate("GenerateTestbedDialog", "0.9"))
        self.groupBox_2.setTitle(_translate("GenerateTestbedDialog", "Link model settings"))
        self.label_6.setText(_translate("GenerateTestbedDialog", "Noise floor [dBm]"))
        self.noisefloorLe.setText(_translate("GenerateTestbedDialog", "-90"))
        self.label_7.setText(_translate("GenerateTestbedDialog", "TX power [dBm]"))
        self.txpowerLe.setText(_translate("GenerateTestbedDialog", "0"))
        self.label_8.setText(_translate("GenerateTestbedDialog", "Wavelength [m]"))
        self.wavelengthLe.setToolTip(_translate("GenerateTestbedDialog", "wavelength = c / f. With a frequency of 2.4 GHz the wavelength is 12.5cm."))
        self.wavelengthLe.setText(_translate("GenerateTestbedDialog", "0.125"))
        self.label_9.setText(_translate("GenerateTestbedDialog", "FSPL Exponent"))
        self.fsplExpLe.setToolTip(_translate("GenerateTestbedDialog", "Sets the exponent in the free space path loss formular. Higher values increase the attenuation."))
        self.fsplExpLe.setText(_translate("GenerateTestbedDialog", "4"))
        self.groupBox_3.setTitle(_translate("GenerateTestbedDialog", "Resulting properties"))
        self.label_10.setText(_translate("GenerateTestbedDialog", "SNR for specified min. PRR [dB]"))
        self.label_12.setText(_translate("GenerateTestbedDialog", "RX sensitivity for min. PRR [dB]"))
        self.label_14.setText(_translate("GenerateTestbedDialog", "Max. distance between nearest neighbors"))
