# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestcasesDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestcasesDialog(object):
    def setupUi(self, TestcasesDialog):
        TestcasesDialog.setObjectName("TestcasesDialog")
        TestcasesDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        TestcasesDialog.resize(967, 912)
        self.verticalLayout = QtWidgets.QVBoxLayout(TestcasesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(TestcasesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.labelLine = QtWidgets.QLineEdit(self.tab)
        self.labelLine.setObjectName("labelLine")
        self.horizontalLayout_5.addWidget(self.labelLine)
        self.horizontalLayout_5.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.testbedLine = QtWidgets.QLineEdit(self.tab)
        self.testbedLine.setObjectName("testbedLine")
        self.horizontalLayout.addWidget(self.testbedLine)
        self.openTestbedBtn = QtWidgets.QPushButton(self.tab)
        self.openTestbedBtn.setObjectName("openTestbedBtn")
        self.horizontalLayout.addWidget(self.openTestbedBtn)
        self.horizontalLayout.setStretch(1, 9)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.numRoundsLine = QtWidgets.QLineEdit(self.tab)
        self.numRoundsLine.setObjectName("numRoundsLine")
        self.horizontalLayout_3.addWidget(self.numRoundsLine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.numSlotsLine = QtWidgets.QLineEdit(self.tab)
        self.numSlotsLine.setObjectName("numSlotsLine")
        self.horizontalLayout_8.addWidget(self.numSlotsLine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setMinimumSize(QtCore.QSize(100, 0))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_11.addWidget(self.label_35)
        self.payloadSizeLine = QtWidgets.QLineEdit(self.tab)
        self.payloadSizeLine.setObjectName("payloadSizeLine")
        self.horizontalLayout_11.addWidget(self.payloadSizeLine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.payloadDistributionLine = QtWidgets.QLineEdit(self.tab)
        self.payloadDistributionLine.setObjectName("payloadDistributionLine")
        self.horizontalLayout_15.addWidget(self.payloadDistributionLine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setMinimumSize(QtCore.QSize(100, 0))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_14.addWidget(self.label_36)
        self.simulationModeBox = QtWidgets.QComboBox(self.tab)
        self.simulationModeBox.setObjectName("simulationModeBox")
        self.horizontalLayout_14.addWidget(self.simulationModeBox)
        self.horizontalLayout_14.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setMinimumSize(QtCore.QSize(100, 0))
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_43.addWidget(self.label_37)
        self.logLevelBox = QtWidgets.QComboBox(self.tab)
        self.logLevelBox.setObjectName("logLevelBox")
        self.horizontalLayout_43.addWidget(self.logLevelBox)
        self.horizontalLayout_43.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setMinimumSize(QtCore.QSize(100, 0))
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_44.addWidget(self.label_38)
        self.logSaveDetailsBox = QtWidgets.QComboBox(self.tab)
        self.logSaveDetailsBox.setObjectName("logSaveDetailsBox")
        self.horizontalLayout_44.addWidget(self.logSaveDetailsBox)
        self.horizontalLayout_44.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_44)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_31.addWidget(self.label_5)
        self.fieldSizeLine = QtWidgets.QLineEdit(self.tab_2)
        self.fieldSizeLine.setObjectName("fieldSizeLine")
        self.horizontalLayout_31.addWidget(self.fieldSizeLine)
        self.horizontalLayout_31.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_31)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setMinimumSize(QtCore.QSize(100, 0))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_32.addWidget(self.label_11)
        self.immediateEliminationBox = QtWidgets.QComboBox(self.tab_2)
        self.immediateEliminationBox.setObjectName("immediateEliminationBox")
        self.horizontalLayout_32.addWidget(self.immediateEliminationBox)
        self.horizontalLayout_32.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_32)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        self.smartShutdownBox = QtWidgets.QComboBox(self.tab_2)
        self.smartShutdownBox.setObjectName("smartShutdownBox")
        self.horizontalLayout_20.addWidget(self.smartShutdownBox)
        self.horizontalLayout_20.setStretch(1, 1)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_19.addWidget(self.line_2)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setMinimumSize(QtCore.QSize(100, 0))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_28.addWidget(self.label_18)
        self.recursiveNeighborhoodBox = QtWidgets.QComboBox(self.tab_2)
        self.recursiveNeighborhoodBox.setObjectName("recursiveNeighborhoodBox")
        self.horizontalLayout_28.addWidget(self.recursiveNeighborhoodBox)
        self.horizontalLayout_28.setStretch(1, 1)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_28)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.historyWindowLengthLine = QtWidgets.QLineEdit(self.tab_2)
        self.historyWindowLengthLine.setObjectName("historyWindowLengthLine")
        self.horizontalLayout_12.addWidget(self.historyWindowLengthLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.fInitiatorLine = QtWidgets.QLineEdit(self.tab_2)
        self.fInitiatorLine.setObjectName("fInitiatorLine")
        self.horizontalLayout_6.addWidget(self.fInitiatorLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8)
        self.fTimeoutLine = QtWidgets.QLineEdit(self.tab_2)
        self.fTimeoutLine.setObjectName("fTimeoutLine")
        self.horizontalLayout_17.addWidget(self.fTimeoutLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setMinimumSize(QtCore.QSize(100, 0))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_21.addWidget(self.label_23)
        self.fTxCurveLine = QtWidgets.QLineEdit(self.tab_2)
        self.fTxCurveLine.setObjectName("fTxCurveLine")
        self.horizontalLayout_21.addWidget(self.fTxCurveLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setMinimumSize(QtCore.QSize(100, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self.exchangeTriggerSparsityLine = QtWidgets.QLineEdit(self.tab_2)
        self.exchangeTriggerSparsityLine.setObjectName("exchangeTriggerSparsityLine")
        self.horizontalLayout_18.addWidget(self.exchangeTriggerSparsityLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_34.addWidget(self.label_13)
        self.allowedUpdatesLine = QtWidgets.QLineEdit(self.groupBox)
        self.allowedUpdatesLine.setObjectName("allowedUpdatesLine")
        self.horizontalLayout_34.addWidget(self.allowedUpdatesLine)
        self.horizontalLayout_34.setStretch(1, 1)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_33.addWidget(self.line_3)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_35.addWidget(self.label_14)
        self.mulOnRxBox = QtWidgets.QComboBox(self.groupBox)
        self.mulOnRxBox.setObjectName("mulOnRxBox")
        self.horizontalLayout_35.addWidget(self.mulOnRxBox)
        self.horizontalLayout_35.setStretch(1, 1)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_35)
        self.verticalLayout_6.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setMinimumSize(QtCore.QSize(100, 0))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_36.addWidget(self.label_15)
        self.mulOnRequestBox = QtWidgets.QComboBox(self.groupBox)
        self.mulOnRequestBox.setObjectName("mulOnRequestBox")
        self.horizontalLayout_36.addWidget(self.mulOnRequestBox)
        self.horizontalLayout_36.setStretch(1, 1)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_36)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_27.addWidget(self.line_4)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_37.addWidget(self.label_16)
        self.mulOnOwnBox = QtWidgets.QComboBox(self.groupBox)
        self.mulOnOwnBox.setObjectName("mulOnOwnBox")
        self.horizontalLayout_37.addWidget(self.mulOnOwnBox)
        self.horizontalLayout_37.setStretch(1, 1)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_37)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setMinimumSize(QtCore.QSize(100, 0))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_38.addWidget(self.label_20)
        self.includeOwnLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.includeOwnLine.setObjectName("includeOwnLine")
        self.horizontalLayout_38.addWidget(self.includeOwnLine)
        self.horizontalLayout_38.setStretch(1, 1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_38)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_13.addWidget(self.line_5)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_39.addWidget(self.label_22)
        self.emptyPacketStrategyBox = QtWidgets.QComboBox(self.groupBox_2)
        self.emptyPacketStrategyBox.setObjectName("emptyPacketStrategyBox")
        self.horizontalLayout_39.addWidget(self.emptyPacketStrategyBox)
        self.horizontalLayout_39.setStretch(1, 1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_39)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setMinimumSize(QtCore.QSize(100, 0))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.fAgeToPLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.fAgeToPLine.setObjectName("fAgeToPLine")
        self.horizontalLayout_22.addWidget(self.fAgeToPLine)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.coordinatedSlottingBox = QtWidgets.QComboBox(self.groupBox_3)
        self.coordinatedSlottingBox.setObjectName("coordinatedSlottingBox")
        self.horizontalLayout_29.addWidget(self.coordinatedSlottingBox)
        self.horizontalLayout_29.setStretch(0, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setMinimumSize(QtCore.QSize(100, 0))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_23.addWidget(self.label_25)
        self.fpOwnLine = QtWidgets.QLineEdit(self.groupBox_3)
        self.fpOwnLine.setObjectName("fpOwnLine")
        self.horizontalLayout_23.addWidget(self.fpOwnLine)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setMinimumSize(QtCore.QSize(100, 0))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_30.addWidget(self.label_26)
        self.fpForeignLine = QtWidgets.QLineEdit(self.groupBox_3)
        self.fpForeignLine.setObjectName("fpForeignLine")
        self.horizontalLayout_30.addWidget(self.fpForeignLine)
        self.horizontalLayout_30.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setMinimumSize(QtCore.QSize(100, 0))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_24.addWidget(self.label_27)
        self.fpInitLine = QtWidgets.QLineEdit(self.groupBox_3)
        self.fpInitLine.setObjectName("fpInitLine")
        self.horizontalLayout_24.addWidget(self.fpInitLine)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setMinimumSize(QtCore.QSize(100, 0))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_40.addWidget(self.label_29)
        self.requestModeBox = QtWidgets.QComboBox(self.groupBox_4)
        self.requestModeBox.setObjectName("requestModeBox")
        self.horizontalLayout_40.addWidget(self.requestModeBox)
        self.horizontalLayout_40.setStretch(1, 1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_40)
        self.line_6 = QtWidgets.QFrame(self.groupBox_4)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_9.addWidget(self.line_6)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setMinimumSize(QtCore.QSize(100, 0))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_41.addWidget(self.label_30)
        self.columnSearchModeBox = QtWidgets.QComboBox(self.groupBox_4)
        self.columnSearchModeBox.setObjectName("columnSearchModeBox")
        self.horizontalLayout_41.addWidget(self.columnSearchModeBox)
        self.horizontalLayout_41.setStretch(1, 1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_41)
        self.line_7 = QtWidgets.QFrame(self.groupBox_4)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_9.addWidget(self.line_7)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setMinimumSize(QtCore.QSize(100, 0))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_42.addWidget(self.label_31)
        self.rxSnoopBox = QtWidgets.QComboBox(self.groupBox_4)
        self.rxSnoopBox.setObjectName("rxSnoopBox")
        self.horizontalLayout_42.addWidget(self.rxSnoopBox)
        self.horizontalLayout_42.setStretch(1, 1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_42)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setMinimumSize(QtCore.QSize(100, 0))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_25.addWidget(self.label_32)
        self.fTxColumnYesNoLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.fTxColumnYesNoLine.setObjectName("fTxColumnYesNoLine")
        self.horizontalLayout_25.addWidget(self.fTxColumnYesNoLine)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setMinimumSize(QtCore.QSize(100, 0))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_26.addWidget(self.label_33)
        self.fTxPivotYesNoLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.fTxPivotYesNoLine.setObjectName("fTxPivotYesNoLine")
        self.horizontalLayout_26.addWidget(self.fTxPivotYesNoLine)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setMinimumSize(QtCore.QSize(100, 0))
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_10.addWidget(self.label_34)
        self.fpHelplessLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.fpHelplessLine.setObjectName("fpHelplessLine")
        self.horizontalLayout_10.addWidget(self.fpHelplessLine)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saveConfigBtn = QtWidgets.QPushButton(TestcasesDialog)
        self.saveConfigBtn.setObjectName("saveConfigBtn")
        self.horizontalLayout_4.addWidget(self.saveConfigBtn)
        self.loadConfigBtn = QtWidgets.QPushButton(TestcasesDialog)
        self.loadConfigBtn.setObjectName("loadConfigBtn")
        self.horizontalLayout_4.addWidget(self.loadConfigBtn)
        self.closeConfigBtn = QtWidgets.QPushButton(TestcasesDialog)
        self.closeConfigBtn.setObjectName("closeConfigBtn")
        self.horizontalLayout_4.addWidget(self.closeConfigBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(TestcasesDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TestcasesDialog)

    def retranslateUi(self, TestcasesDialog):
        _translate = QtCore.QCoreApplication.translate
        TestcasesDialog.setWindowTitle(_translate("TestcasesDialog", "Testcase Configuration"))
        self.label_4.setText(_translate("TestcasesDialog", "Config name"))
        self.label.setText(_translate("TestcasesDialog", "Testbed"))
        self.openTestbedBtn.setText(_translate("TestcasesDialog", "Open Testbed"))
        self.label_2.setText(_translate("TestcasesDialog", "numRounds"))
        self.label_3.setText(_translate("TestcasesDialog", "numSlots"))
        self.label_35.setText(_translate("TestcasesDialog", "payloadSize"))
        self.label_6.setText(_translate("TestcasesDialog", "payloadDistribution"))
        self.label_36.setText(_translate("TestcasesDialog", "simulationMode"))
        self.label_37.setText(_translate("TestcasesDialog", "logLevel"))
        self.label_38.setText(_translate("TestcasesDialog", "logSaveDetails"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TestcasesDialog", "Application Config"))
        self.label_5.setText(_translate("TestcasesDialog", "fieldSize"))
        self.label_11.setText(_translate("TestcasesDialog", "immediateElim."))
        self.label_17.setText(_translate("TestcasesDialog", "smartShutdown"))
        self.label_18.setText(_translate("TestcasesDialog", "recursiveNeighb."))
        self.label_9.setText(_translate("TestcasesDialog", "historyWindowLen."))
        self.label_7.setText(_translate("TestcasesDialog", "fInitiator"))
        self.label_8.setText(_translate("TestcasesDialog", "fTimeout"))
        self.label_23.setText(_translate("TestcasesDialog", "fTxCurve"))
        self.label_10.setText(_translate("TestcasesDialog", "exchangeTriggerSp."))
        self.groupBox.setTitle(_translate("TestcasesDialog", "fastTxUpdate"))
        self.label_13.setText(_translate("TestcasesDialog", "allowedUpdates"))
        self.label_14.setText(_translate("TestcasesDialog", "mulOnRx"))
        self.label_15.setText(_translate("TestcasesDialog", "mulOnRequest"))
        self.label_16.setText(_translate("TestcasesDialog", "mulOnOwn"))
        self.groupBox_2.setTitle(_translate("TestcasesDialog", "txPacket"))
        self.label_20.setText(_translate("TestcasesDialog", "includeOwn"))
        self.includeOwnLine.setToolTip(_translate("TestcasesDialog", "-1 = always, 0 = unenforced, x>0 = until x times received (acked)"))
        self.label_22.setText(_translate("TestcasesDialog", "emptyPacketStrat."))
        self.label_21.setText(_translate("TestcasesDialog", "fAgeToP"))
        self.groupBox_3.setTitle(_translate("TestcasesDialog", "coordinatedSlotting"))
        self.label_25.setText(_translate("TestcasesDialog", "fpOwn"))
        self.label_26.setText(_translate("TestcasesDialog", "fpForeign"))
        self.label_27.setText(_translate("TestcasesDialog", "fpInit"))
        self.groupBox_4.setTitle(_translate("TestcasesDialog", "request"))
        self.label_29.setText(_translate("TestcasesDialog", "mode"))
        self.label_30.setText(_translate("TestcasesDialog", "columnSearchMode"))
        self.label_31.setText(_translate("TestcasesDialog", "rxSnoop"))
        self.label_32.setText(_translate("TestcasesDialog", "fTxColumnYesNo"))
        self.label_33.setText(_translate("TestcasesDialog", "fTxPivotYesNo"))
        self.label_34.setText(_translate("TestcasesDialog", "fpHelpless"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TestcasesDialog", "Internal Config"))
        self.saveConfigBtn.setText(_translate("TestcasesDialog", "Save current configuration"))
        self.loadConfigBtn.setText(_translate("TestcasesDialog", "Load existing configuration"))
        self.closeConfigBtn.setText(_translate("TestcasesDialog", "Close"))


