# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestbedDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestbedDialog(object):
    def setupUi(self, TestbedDialog):
        TestbedDialog.setObjectName("TestbedDialog")
        TestbedDialog.resize(1200, 800)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TestbedDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(TestbedDialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(TestbedDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.graphicsView = QtWidgets.QGraphicsView(TestbedDialog)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.lineEdit_2 = QtWidgets.QLineEdit(TestbedDialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 2)

        self.retranslateUi(TestbedDialog)
        QtCore.QMetaObject.connectSlotsByName(TestbedDialog)

    def retranslateUi(self, TestbedDialog):
        _translate = QtCore.QCoreApplication.translate
        TestbedDialog.setWindowTitle(_translate("TestbedDialog", "Testbed Configuration"))
        self.pushButton.setText(_translate("TestbedDialog", "generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestbedDialog = QtWidgets.QDialog()
    ui = Ui_TestbedDialog()
    ui.setupUi(TestbedDialog)
    TestbedDialog.show()
    sys.exit(app.exec_())
